import urllib.request, json
r = urllib.request.urlopen('http://localhost:4000/api/bot/status')
d = json.loads(r.read())
hb = d.get('heartbeat', {})
print('=== SHADOW FIELDS ===')
print('shadowInTrade:', hb.get('shadowInTrade'))
print('shadowDir:', hb.get('shadowDir'))
print('shadowEntry:', hb.get('shadowEntry'))
print('shadowPnL:', hb.get('shadowPnL'))
print('shadowTrades:', hb.get('shadowTrades'))
print('shadowWins:', hb.get('shadowWins'))
print('shadowLosses:', hb.get('shadowLosses'))
print('shadowSL:', hb.get('shadowSL'))
print('=== SCALP1 FIELDS ===')
print('scalp1InTrade:', hb.get('scalp1InTrade'))
print('scalp1Dir:', hb.get('scalp1Dir'))
print('scalp1Entry:', hb.get('scalp1Entry'))
print('scalp1PnL:', hb.get('scalp1PnL'))
print('scalp1Trades:', hb.get('scalp1Trades'))
print('scalp1SL:', hb.get('scalp1SL'))
print('=== MAIN ===')
print('inTrade:', hb.get('inTrade'))
print('livePrice:', hb.get('livePrice'))
print('=== TOP-LEVEL KEYS ===')
print(list(d.keys()))
