const fs = require('fs');
const clean = {
  savedAt: new Date().toISOString(),
  earlyEntryDone: false,
  mainEntryDone: false,
  activeTrade: false,
  pyramidDone: false,
  tradeDirection: null,
  tradeSymbol: null,
  entryPrice: null,
  earlyQty: 0,
  mainQty: 0,
  pyramidQty: 0,
  entryTime: null,
  entrySlippage: 0,
  tradeAIScore: 0,
  tradeCount: 0,
  dailyPnL: 0,
  consecutiveLosses: 0,
  lastTradeProfit: false,
  trendMode: false,
  candleSL: 0,
  trailActivated: false,
  rcWaiting: false,
  rcBreakoutDir: null,
  rcTrade2Active: false,
  rcIndexSL: 0,
  entryPremium: 0,
  shadowPnL: 0,
  shadowTrades: 0,
  shadowWins: 0,
  shadowLosses: 0,
  shadowTradeLog: [],
  scalp1PnL: 0,
  scalp1Trades: 0,
  scalp1Wins: 0,
  scalp1Losses: 0,
  scalp1TradeLog: [],
  lock50ShadowState: { inTrade: false, dir: null, entry: 0, sl: 0 },
  lock50Wins: 0,
  lock50Losses: 0,
  lock50TradeLog: [],
  hybridState: { inTrade: false, dir: null, entry: 0, sl: 0, refHigh: 0, firstDone: false, reUsed: false, waitReEntry: false, isC1: false }
};
fs.writeFileSync('/home/ubuntu/trading-bot/trade-state.json', JSON.stringify(clean, null, 2));
console.log('trade-state.json cleared');
